apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY:    "Replace_me"
  DATABASE_URL:  "postgres://user:password@host:port/dbname"
  DEBUG:         "False"
  ALLOWED_HOSTS: "*"

