apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30031
      protocol: TCP
