apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
  labels:
    app.kubernetes.io/name: django-app
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 15
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django-app
        spec:
          containers:
          - name   : django-app
            image  : forluc/django_app
            envFrom:
              - secretMapRef:
                  name: django-secret
              - configMapRef:
                  name: django-configmap
            imagePullPolicy: IfNotPresent
            command:
            - ./manage.py
            - clearsessions
          restartPolicy: OnFailure